services:
  crypto-service:
    build: 
      context: ./crypto-service-python
      dockerfile: Dockerfile
    container_name: crypto-service
    # ports:
    #   - "8002:8002"
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - JWT_SECRET=${JWT_SECRET}

  auth-service:
    build: ./auth-service-dotnet
    container_name: auth-service
    # ports:
    #   - "8001:8001" 
  api-gateway:
    build: ./api-gateway-dotnet
    container_name: api-gateway
    # ports:
    #   - "8000:8000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - auth-service
      - crypto-service 
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend-react/dist:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway
