version: "3.9"

services:
  crypto-service:
    build: 
      context: ./crypto-service-python
      dockerfile: Dockerfile
    container_name: crypto-service
    ports:
      - "8002:8002"
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - JWT_SECRET=${JWT_SECRET}

  auth-service:
    build: ./auth-service-dotnet
    container_name: auth-service
    ports:
      - "8001:8001"  