services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "16686:16686"  # Web UI
      - "14268:14268"  # HTTP collector
      - "14250:14250"  # gRPC collector
      - "6831:6831/udp"  # UDP port for Jaeger agent

  crypto-service:
    build: 
      context: ./crypto-service-python
      dockerfile: Dockerfile
    container_name: crypto-service
    environment:
      - FERNET_KEY=${FERNET_KEY}
      - JWT_SECRET=${JWT_SECRET}

  auth-service:
    build: ./auth-service-dotnet
    container_name: auth-service

  api-gateway:
    build: ./api-gateway-dotnet
    container_name: api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - jaeger  # Add this dependency
      - auth-service
      - crypto-service

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend-react/dist:/usr/share/nginx/html:ro
    depends_on:
      - api-gateway